### DISCUSSION TITLE
OCM Proposal Spec - Current Pain Points

### DISCUSSION THREAD

**Discussion by In-Ko** [open-component-model/ocm#15] [General]
This thread is to consolidate all the things of the OCM proposal spec, which are problematic, unclear, need rephrasing, need examples, and so on ... Let's gather everything here, and then have a meeting to discuss all these points and agree on how to improve them.

**Comment by jensh007** [comment]
https://github.com/gardener/component-spec/blob/master/doc/proposal/02-component-descriptor.md#references
I am confused here. First: spending one short sentence on one of the fundamental OCM concepts is perhaps not enough. Second:  A few lines later there is an example but it comes without any explanation. What do we want to express with:

```
- name: external-monitoring
      version: v0.8.3
      relation: external
```

Third:
Components versions are typically built from sources, maintained in source code management systems, and transformed into resources (for example by a build), which are used at installation or runtime of the product.
Okay I have code, a build and an output like a container image. But apparently there is more: Things like a blueprint for landscaper or a helm chart being not "built from source"? If I look at the logging component-descriptor example I posted in the teams share it declares some kind of dependencies, e.g.

```
  resources:
    - name: fluent-bit-to-loki
      version: v0.40.0
      type: ociImage
      access:
        type: ociRegistry
        imageReference: >-
          eu.gcr.io/sap-se-gcr-k8s-public/eu_gcr_io/gardener-project/gardener/fluent-bit-to-loki:v0.40.0-mod1
      digest: null
      extraIdentity: {}
      relation: local
      labels:
        - name: cloud.gardener.cnudie/migration/original_ref
          value: eu.gcr.io/gardener-project/gardener/fluent-bit-to-loki:v0.40.0
        - name: cloud.gardener.cnudie/sdo/lssd
          value:
            processingRules:
              - purge_berkeleydb_to_public
      srcRefs: []
```

Dependencies are not mentioned at all. When do I declare a dependency as a resource and when as component reference then?

```
component:
  componentReferences:
  - name: name-1
    componentName: github.com/.../component-name-1
    version: v1.38.3
  - name: name-2
    componentName: .../component-name-2
    version: v0.11.4 
```

Can't we give a real example here? I feel this is entirely meaningless ...?
IMHO this section needs a bit of rephrasing. I doubt that a reader of the spec can create a valid component-descriptor with just this information.

**Reply by yitsushi** [reply]
As I understand:
1. you define a resource if it's a resource of the component, like a docker image or a helm chart.
2. you define componentReferences, if you want to refer to another component

Based on this logic, a very simple example:

```
application.prod/
  resources:
    - application container image
    - sidecar container image
  componentReferences:
    - github.com/..../database.prod

database.prod/
  resources:
    - database container image
  componentReferences: []
```

Here we have an application component, but to use that application.prod component, we need the database.prod component.

Correct me if I'm wrong.

Side note: I assume `componentReferences` does NOT work with directory or tar.gz archives only with full oci document path. Why? Because the directory name and the component name are different (can be different) and in this case of `database.prod` is a local directory component, `application.prod` has no way to know where `database.prod` component is.

**Reply by yitsushi** [reply]
With `--lookup` flag ( more info from @Skarlso ) local directory reference is working as well.

**Reply by Skarlso** [reply]
I defined the following component desc in folder `test-ocm`:

```yaml
component:
  componentReferences:
    - name: dependency
      componentName: test.ref/ # additional name component missing
      version: 0.0.1
  name: skarlso.test/
  provider: skarlso
  repositoryContexts: []
  resources:
  - access:
      imageReference: docker.io/skarlso/ocm:example-0.0.1
      type: ociRegistry
    name: ocm-hello-server
    relation: external
    type: ociImage
    version: 0.0.1
  - access:
      imageReference: docker.io/skarlso/ocm:example-0.0.1
      type: ociRegistry
    name: ocm-hello-1
    relation: external
    type: ociImage
    version: 0.0.1
  sources: []
  version: 0.0.1
meta:
  schemaVersion: v2
```

tree:
```
tree test-ocm
test-ocm
├── blobs
└── component-descriptor.yaml

1 directory, 1 fil
```

Then test-ref is another component:
```yaml
component:
  componentReferences: []
  name: test.ref/
  provider: skarlso
  repositoryContexts: []
  resources:
  - access:
      imageReference: docker.io/skarlso/ocm:example-0.0.1
      type: ociRegistry
    name: ocm-hello-db
    relation: external
    type: ociImage
    version: 0.0.1
  sources: []
  version: 0.0.1
meta:
  schemaVersion: v2
```

tree:
```
tree test-ref
test-ref
├── blobs
└── component-descriptor.yaml

1 directory, 1 file
```

Then I ran a recursive download in the first component by defining the local ref component as a lookup option:

```
 ocm download resources test-ocm --lookup test-ref -c
Warning: lookup nested component "test.ref/" [skarlso.test/:0.0.1]: component "test.ref/" not found in ComponentArchive
Downloading:  skarlso.test/0.0.1/ocm-hello-server ocm-hello-server OsFs
skarlso.test/0.0.1/ocm-hello-server: 781397 byte(s) written
Downloading:  skarlso.test/0.0.1/test.ref/0.0.1/ocm-hello-db ocm-hello-db OsFs
skarlso.test/0.0.1/test.ref/0.0.1/ocm-hello-db: 781397 byte(s) written
```

That worked. :)

**Reply by jensh007** [reply]
>     2. you define componentReferences, if you want to refer to another component
> 
> 
Okay but:
As I understand it a componentReference is always a reference to another component descriptor.
So what happens if the component I depend on does not know anything about OCM? Is it then a component resource?
Let's say I need nginx and nginx does not have any cd...

**Reply by yitsushi** [reply]
componentReference is a component reference, you can specify only ocm components there.

In the nginx case:
Options A) I would say create a new component that wraps nginx and refer to that component.
Options B) Make it part of the original component and define it as a resource.

**Reply by yitsushi** [reply]
Like if a helm chart is depend on something, it has to be deployed with that helm chart or another helm chart is added as dependency. You can't just add nginx as dependency to your helm chart if it does not have a helm chart. You can create an nginx helm chart or you can embed nginx in your helm chart directly.

**Comment by Skarlso** [comment]
I see it the same way as Balazs said. If it is a dependency, I would wrap it around a component descriptor, however........

## Argument for Explicit dependency declaration

Right now, the references are only traversed and then added as a list that is then processed in that order. There is no topological order in between them, so you don't know which component depends on which. The only thing that happens right now in `ocm` for these references is that it checks if they can be found or not and runs some validations on them.

It's also used in some other circumstances but there is no dependency declaration and the order is not guaranteed.

There is an argument that the dependencies should be taken care of outside the schema definition but I disagree on that. I believe as Paul put it, it would be beneficial to define explicit dependencies as other specs do such as cyclonedx's dependency graph for example. 

### What would we need

We would need something that declares dependencies. Right now, references in code are called dependencies, but they are only such in the sense of references and declaration. And not further processing. We have two options:

#### Renamed `ComponentReferences` to `ComponentDependencies`

This would include a large amount of code change in OCM right now as we adjust existing code around this idea. We would have to change how processing is done and how various commands evaluate dependencies. There is already an embedded field in all objects called `History` which technically, could be used for this purpose and indeed the `tree` output already uses it to construct a graph. 

#### Introduce a new field

This would be preferred as this is the least impact on existing code and schema structure. Something like:

`dependencyReferences` would take a list of depending component names and versions. This could then be used to construct a tree which, in turn, could be passed down to the processing command at the end of the processing chain. This tree could be constructed in between steps and forwarded and then used during the final action run.

### Large amount of work in either case

Processing in commands would have to be adjusted to deal with dependencies first, and then the dependent. There is nothing in processing that is aware of any kind of structure so in either case, it will have to be a large amount of work.

## Conclusion 

I believe that dependencies in any kind of software component context cannot be ignored or deferred as they are just part of the life of a software product. You have to have X before Y can even begin to be installed. There is no real way around that.

**Comment by nab-gha** [comment]
I would add a new field to the `Resources` and `ComponentReferences` called `dependsOn` which would be a list of other Resources and ComponentReferences in the same component descriptor that it depends on. Like flux's HelmReleases and Kustomizations the dependant object should define what it depends on

**Reply by yitsushi** [reply]
Based on the initial spec, it does not make sense to allow `Resources` to be listed as dependencies. They are part of the component, the component by logic does not depend on it's pieces, the component will use its pieces and build up something.

I would draw similarity with helm charts:
1. A helm chart can have other dependencies and those are all helm charts.
2. A helm chart can have resources and no no dependency defined between them, they are the resources this helm chart manages.

**Reply by In-Ko** [reply]
> Based on the initial spec, it does not make sense to allow `Resources` to be listed as dependencies. They are part of the component, the component by logic does not depend on it's pieces, the component will use its pieces and build up something.
> 
> I would draw similarity with helm charts:
> 
> 1. A helm chart can have other dependencies and those are all helm charts.
> 2. A helm chart can have resources and no no dependency defined between them, they are the resources this helm chart manages.

I think this nails it. Everything that is listed as a resource within one component formally belongs to that component. This can be docker images, helm charts, content packages, whatever else. Simply everything that makes up this specific component. This resources list can in itself be divided into two "flavours": The complete list of artifacts, including things like content packages, which are not necessarily needed at deploytime. The other flavour is the list of artifacts, which are absolutely required for a successful deployment. The specification does not have this distinction as of now (and maybe does not need), just wanted to mentioned these two different flavours of these "internal dependencies".
Then, we have the requirement to model external dependencies, which are usually runtime dependencies (e.g. certain service instances which need to be ordered during runtime). These are not listed within the resources section at all, for those, we need an additional model on top (as a separate type of artifact), which can be shipped with the component, and some controller can process these "runtime dependency" artifact and do the needful.
"Component References" should be used to build up a hierarchy of components, so that it will become possible to ship a complete "Gardener" simply by specifying one "Gardener Component" as top-level component, which then references all components it entails.

**Reply by phoban01** [reply]
So a LAMP-(ish) stack would be modelled something like the following:
```mermaid
erDiagram
    NGINX-COMPONENT ||--|| NGINX-BINARY : "has-resource"
    NGINX-COMPONENT ||--|| NGINX-CONF : "has-resource"
    NGINX-COMPONENT ||--|| APPLICATION-CODE : "has-resource"
    NGINX-COMPONENT ||--|| GITHUB-APP-REPOSITORY : "has-source"

    PHP-COMPONENT ||--|| PHP-FPM-BINARY : "has-resource"
    PHP-COMPONENT ||--|| INI-FILE : "has-resource"

    MySQL-COMPONENT ||--|| MYSQL-BINARY : "has-resource"

    LINUX-COMPONENT ||--|| UBUNTU-OCI-IMAGE : "has-resource"

    LAMP-STACK-COMPONENT ||--|| NGINX-COMPONENT : "has-component-reference"

    NGINX-COMPONENT ||--|| PHP-COMPONENT : "has-component-reference"
    NGINX-COMPONENT ||--|| LINUX-COMPONENT : "has-component-reference"

    PHP-COMPONENT ||--|| MySQL-COMPONENT : "has-component-reference"
    PHP-COMPONENT ||--|| LINUX-COMPONENT : "has-component-reference"

    MySQL-COMPONENT ||--|| LINUX-COMPONENT : "has-component-reference"

    NGINX-COMPONENT {
        version v1-0-0
    }

    PHP-COMPONENT {
         version v1-0-0
    }

    MySQL-COMPONENT {
         version v1-0-0
    }

    LINUX-COMPONENT {
         version v1-0-0
    }

```

**Reply by yitsushi** [reply]
I'm not sure I understand all parts of this graph. I don't think the MySQL component would and PHP has a dependency connection between them, and I don't know what is the Linux  Component with Ubuntu.

I try to approach this from the point I understand (which may not be true):

```yaml
# assume that's the ubuntu container there
ApplicationComponent:
  resources: ubuntu-oci-image
  componentReferences:
    - NginxComponent
    - PHPComponent
    - MySQLComponent

NginxComponent:
  resources: [all the listed resources]
  # I don't think it depends on the PHP component, the application does, nginx is happy alone
  componentReferences: []

# i don't know what's the point of this, it can be part of the application container
# in a bare metal environment, it's just php installation and configuration, no dependencies,
# php can run without the application, nginx, or mysql
PHPComponent:
  resources: [all the listed resources]
  # it can depend on mysql libs, but I think it can be handled here
  componentReferences: []

MySQLComponent:
  resources: [all the listed resources]
  # no dependencies because mysql is happy to run, the application depends on the database
  componentReferences: []
```

With this, when I try to deploy `ApplicationComponent`, it will walk through all referenced ones and deploy them[^1]. The deployment flow will be something like:
1. `Start` deploying `ApplicationComponent`.
2. `Suspend` deploying `ApplicationComponent`.
3. `Start` deploying `NginxComponent`.
4. `Start` deploying `PHPComponent`.
5. `Finish` deploying `NginxComponent`.
6. `Start` deploying `MySQLComponent`.
7. `Finish` deploying `PHPComponent`.
8. `Finish` deploying `MySQLComponent`.
9. `Continue` deploying `ApplicationComponent`.
10. `Finish` deploying `ApplicationComponent`.

At the same time, some of the resources of components can be part of the ApplicationComponent, like host specific nginx config, or app specific php-fpm pool defintion.

[^1]: Right now I don't think the system waits for component references to be deployed successfully before proceeds with the deployment of the component itself, but it should do that.
