### ISSUE TITLE
Cannot add references in `component-constructor.yaml` file as part of component version specification

### ISSUE THREAD

**Issue by jakobmoellerdev** [open-component-model/ocm#1041]
**What happened**:

Try to use a `component-constructor.yaml` as such:

```yaml
components:
  - name: github.com/jakobmoellerdev/testcomponent
    version: 1.0.0
    provider:
      name: github.com/jakobmoellerdev
    resources:
      - name: image
        type: ociImage
        version: "1.0"
        access:
          type: ociArtifact
          imageReference: gcr.io/google-containers/echoserver:1.10
    references:
      - name: installer
        componentName: github.com/jakobmoellerdev/toi/installers/helminstaller
        version: 1.0.0
```

Then we try to establish the componentversion as such:

```
ocm add componentversions --create --file ./ctf component-constructor.yaml
```

we then get the following issue:

```
processing component-constructor.yaml...
  processing document 1...
    processing index 1
Error: component-constructor.yaml: invalid component spec 1[1]: references: Forbidden: unknown field
```

**What you expected to happen**:

A successfully added component version

**How to reproduce it (as minimally and precisely as possible)**:

1. attempt to add references as described in https://github.com/open-component-model/ocm-spec/blob/main/doc/01-model/02-elements-toplevel.md#references as part of a component version via component-constructor.

**Anything else we need to know**:

**Environment**:

```
ocm version
{"Major":"0", "Minor":"17", "Patch":"0", "PreRelease":"dev", "Meta":"0d76b3cf563e50cbbf178d213ea9e45ceef40d21", "GitVersion":"0.17.0-dev+0d76b3cf563e50cbbf178d213ea9e45ceef40d21", "GitCommit":"0d76b3cf563e50cbbf178d213ea9e45ceef40d21", "GitTreeState":"dirty", "BuildDate":"2024-10-30T14:56:17+0000", "GoVersion":"go1.23.2", "Compiler":"gc", "Platform":"darwin/arm64"}
```
