### ISSUE TITLE
OCM Controller PoC

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm#114]
Dedicated board: https://github.com/orgs/open-component-model/projects/2
# Overview

The aim of the ocm-controller proof-of-concept is to recreate the AWS OCM-Flux demo using the provider pattern. We will create a new ocm-controller which manages Components and makes their resources available for consumption downstream. The ocm-controller will also manage storage for resource snapshots.

We will introduce two new API types `Source` and `Action` of which providers can create sub-types that satisfy a contract defined by the ocm-controller. Provider _Sources_ and _Actions_ will read and write to the storage provided by the ocm-controller. This design will enable any `Source` or `Action` to be consumed by any subsequent `Action`, with complete customization of the implementation details.

The PoC will demonstrate the concept by creating four provider resources: `OCMResource`, `Localizer`, `Configurator` and `KustomizationTemplate`. Using these controllers it should be possible to reproduce the end-to-end OCM demo.

**sub-tasks**:
- [ ] OCM Core Controller #111 
- [ ] Transform Provider #112
- [ ] Flux Provider #113

### Sub-type architecture
The diagram below illustrates the relationships between Sources, Actions and provider resources:

![subtypes-arch-end-to-end drawio](https://user-images.githubusercontent.com/4415593/189648948-484b2f0f-79f0-46c6-a48c-0889a49570aa.png)

### Sample workflow with Custom Resources

To recreate the end-to-end demo the following resources would be checked-in a repository managed by flux. (We assume that all controllers are already running.)

The demo illustrates how the component described [here](https://github.com/open-component-model/demo/tree/main/components/fluxdemo) can be deployed using Flux.

The component is a podinfo application and contains three resources:
- the podinfo container image (type: `ociImage`)
- kubernetes manifests to deploy the podinfo service (type: `kustomize.ocm.fluxcd.io`)
- a package file describing configuration parameters for ocm instance deployment (type: `package.ocm.fluxcd.io`)

The component is built and transfered to the consumer repository. A `ComponentSource` is used to store the `ComponentDescriptor` in the Kubernetes API. The package file is also stored, either as a ConfigMap or a new custom resource.

Sources and Actions can subsequently refer to the`ComponentSource` in order to read the `ComponentDescriptor` and deploy package.

#### Walkthrough

First of all we create the `ComponentSource`. This will retrieve the Component Descriptor from the OCM repository and store the `ComponentDescriptor` and deploy package in the Kubernetes API:

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSource
metadata:
  name: weave-gitops
  namespace: weave-gitops-system
spec:
  interval: 10m
  name: github.com/weaveworks/weave-gitops
  version: v0.9.x
  verify:
    secretRef:
      name: my-public-key
status:
  componentDescriptor: weave-gitops-system/github-com-weaveworks-wge-v0-9-4
  deployPackage: weave-gitops-system/github-com-weaveworks-wge-v0-9-4-deploy-config
  verified: true
```
Next we will add a create `Source` referencing our `ComponentSource` and then create the provider (`ComponentResource`) which will extract the desired resource and store the snapshot:

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Source
metadata:
  name: ui-server
  namespace: wge-system
spec:
  componentRef:
    name: weave-gitops
    namespace: wge-system
  providerRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: ComponentResource
    name: wge-ui-server
status:
  ready: true
  snapshot: string
```

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentResource
metadata:
  name: wge-ui-server
  namespace: wge-system
spec:
  resource: wge-ui-server
status:
  ready: true
  snapshot: string
```

Now we will create an `Action` to localize the `Source`:
```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Action
metadata:
  name: localizer
  namespace: wge-system
spec:
  componentRef:
    name: wge
    namespace: wge-admin
  sourceRef:
    name: wge-admin-source
  providerRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Localization
    name: wge-localizer
status:
  ready: true
  snapshot: string
```

Here we create the provider for the `Action`:
```yaml
apiVersion: x-delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: wge-localizer
  namespace: wge-system
spec: {}
status:
  ready: true
  snapshot: string
```
Next we provide the configuration `Action`, notice we use the `localizer` action as the `sourceRef`:

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Action
metadata:
  name: config
  namespace: wge-system
spec:
  componentRef:
    name: wge
    namespace: wge-admin
  sourceRef:
    name: localizer
  providerRef:
    apiVersion: x-delivery.ocm.software/v1alpha1
    kind: Configurator
    name: wge-config
status:
  ready: true
  snapshot: string
```

```yaml
apiVersion: x-delivery.ocm.software/v1alpha1
kind: Configurator
metadata:
  name: wge-config
  namespace: wge-system
spec:
  values:
  - debug: false
    rate_limit: false
    allowed_domains:
    - example.io
status:
  ready: true
  snapshot: string
```
Finally we create an action for our Flux deployer:

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Action
metadata:
  name: deployer
  namespace: wge-system
spec:
  componentRef:
    name: wge
    namespace: wge-admin
  sourceRef:
    name: config
  providerRef:
    apiVersion: x-delivery.ocm.software/v1alpha1
    kind: KustomizationTemplate
    name: wge-config
status:
  ready: true
  snapshot: string
```
Finally we create the `KustomizationTemplate` resource:
 
```yaml
apiVersion: x-delivery.ocm.software/v1alpha1
kind: KustomizationTemplate
metadata:
  name: wge-deploy
spec:
  template:
    interval: 10m
    path: ./kubernetes
    targetNamespace: my-application-ns
status:
  ready: true
  snapshot: string
```
