### ISSUE TITLE
Bug: `+` in component version is replaced by `.build-`

### ISSUE THREAD

**Issue by hilmarf** [open-component-model/ocm#1235]
**What happened**:

During `ocm transfer` the cv version: `0.0.1-20250108132333+af79499`, gets changed to: `0.0.1-20250108132333.build-af79499`

**What you expected to happen**:

I didn't expect that `+` is replaced by `.build-`. Why is that happening fully automatic?

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
--- # component-constructor.yaml
components:
  - name: docker.io/recmo/docker-hello-tiny
    version: 0.0.1-20250108132333+af79499
    provider:
      name: recmo
    resources:
      - name: docker-hello-tiny
        version: v1.0
        type: ociImage
        access:
          type: ociArtifact
          imageReference: docker.io/recmo/docker-hello-tiny:latest
```

```bash
ocm add cv -c -F .\tmp\ .\component-constructor.yaml
ocm transfer cv .\tmp\ ocm-oci-test.int.repositories.cloud.sap
```

**Error**:

```bash
ocm get cv ocm-oci-test.int.repositories.cloud.sap//docker.io/recmo/docker-hello-tiny:0.0.1-20250108132333.build-af79499 -o yaml
```

closing session: unable to close: closing docker.io/recmo/docker-hello-tiny:0.0.1-20250108132333.build-af79499: unable to unref last: unable to cleanup component version  docker.io/recmo/docker-hello-tiny/0.0.1-20250108132333.build-af79499 while unref last: closing component version docker.io/recmo/docker-hello-tiny:0.0.1-20250108132333.build-af79499: check failed: component version "0.0.1-20250108132333+af79499" is invalid

**Environment**:

**Comment by ikhandamirov** [comment]
I suppose, the '+' character is not allowed in the version as per specification:
```
Image tags consist of lowercase and uppercase letters, digits, underscores (_), periods (.), and dashes (-). It can be up to 128 characters long. And must follow the next regex pattern: [a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}
```
and therefore getting replaced. See also: https://kubernetes.io/docs/concepts/containers/images/

**Comment by ikhandamirov** [comment]
Same in the OCI spec:
```
Throughout this document, <reference> as a tag MUST be at most 128 characters in length and MUST match the following regular expression:

[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}
```

https://github.com/opencontainers/distribution-spec/blob/main/spec.md#workflow-categories

**Comment by hilmarf** [comment]
@ikhandamirov thanks for those!

Weird, why OCM isn't following here semver... [semver.org clearly allows `+` as separator for Build metadata](https://semver.org/#spec-item-10).

**Comment by morri-son** [comment]
@hilmarf I'm not able to reproduce the issue. I can create, transfer and then get the CV from the target registry with the version `0.0.1-20250108132333+af79499` you specified in your example:

```
❯ cat comp.yaml
components:
- name: ocm.software/test2
  version: 0.0.1-20250108132333+af79499
  provider:
    name: internal
  resources:
    - name: docker-hello-tiny
      version: v1.0
      type: ociImage
      access:
        type: ociArtifact
        imageReference: docker.io/recmo/docker-hello-tiny:latest

❯ ocm add cv -c --file ./ctf comp.yaml
processing comp.yaml...
  processing document 1...
    processing index 1
found 1 component
adding component ocm.software/test2:0.0.1-20250108132333+af79499...
  adding resource ociImage: "name"="docker-hello-tiny","version"="v1.0"...

❯ ocm transfer ctf ./ctf ocm-test.int.repositories.cloud.sap/d032990
transferring component "ocm.software/test2"...
  transferring version "ocm.software/test2:0.0.1-20250108132333+af79499"...
  ...adding component version...

❯ ocm get cv ocm-test.int.repositories.cloud.sap/d032990//ocm.software/test2:0.0.1-20250108132333+af79499 -oyaml
---
component:
  componentReferences: []
  creationTime: "2025-01-10T13:01:55Z"
  name: ocm.software/test2
  provider: internal
  repositoryContexts:
  - baseUrl: ocm-test.int.repositories.cloud.sap
    componentNameMapping: urlPath
    subPath: d032990
    type: OCIRegistry
  resources:
  - access:
      imageReference: docker.io/recmo/docker-hello-tiny:latest
      type: ociArtifact
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: ociArtifactDigest/v1
      value: c6be339a02a039f6ceac6b749568a2b4e76c619a2827e11b46da8745e72cd7af
    name: docker-hello-tiny
    relation: external
    type: ociImage
    version: v1.0
  sources: []
  version: 0.0.1-20250108132333+af79499
meta:
  schemaVersion: v2

**Comment by hilmarf** [comment]
@morri-son, that's maybe the case because the version gets converted back, when calling `ocm get`. But please check your component-descriptors in the repo: 

![Image](https://github.com/user-attachments/assets/0f204176-d06f-4ee3-8ed1-c5b771993855)

**Comment by hilmarf** [comment]
```bash
ocm get cv ocm-oci-test.int.repositories.cloud.sap//docker.io/recmo/docker-hello-tiny:0.0.1-20250108132333.build-af79499 -o yaml
```

fails for me with:

```text
Error: closing session: unable to close: closing docker.io/recmo/docker-hello-tiny:0.0.1-20250108132333.build-af79499: unable to unref last: unable to cleanup component version  docker.io/recmo/docker-hello-tiny/0.0.1-20250108132333.build-af79499 while unref last: closing component version docker.io/recmo/docker-hello-tiny:0.0.1-20250108132333.build-af79499: check failed: component version "0.0.1-20250108132333+af79499" is invalid
```

although the returned yaml looks like this:

```yaml
---
component:
  componentReferences: []
  creationTime: "2025-01-09T11:20:47Z"
  name: docker.io/recmo/docker-hello-tiny
  provider: recmo
  repositoryContexts:
  - baseUrl: ocm-oci-test.int.repositories.cloud.sap
    componentNameMapping: urlPath
    type: OCIRegistry
  resources:
  - access:
      imageReference: ocm-oci-test.int.repositories.cloud.sap/recmo/docker-hello-tiny:latest@sha256:c6be339a02a039f6ceac6b749568a2b4e76c619a2827e11b46da8745e72cd7af
      type: ociArtifact
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: ociArtifactDigest/v1
      value: c6be339a02a039f6ceac6b749568a2b4e76c619a2827e11b46da8745e72cd7af
    name: docker-hello-tiny
    relation: external
    type: ociImage
    version: v1.0
  sources: []
  version: 0.0.1-20250108132333+af79499
meta:
  schemaVersion: v2
```
