### ISSUE TITLE
Compatibility issue with v0.18.0 and the main branch

### ISSUE THREAD

**Issue by mandelsoft** [open-component-model/ocm#1245]
**What happened**:

I have a component version build with v0.18.0 and want to hash it with the `main` version of the CLI (commit e31807141) using one of the traditional normalizations (v1 or v2).

This results in an error: ` failed propagating digest context: digest set for github.com/mandelsoft/test1:1.0.0 does not match` .
With version v0.18.0 and v0.19.0 a hash is provided as expected, and both hashes are identical.

**What you expected to happen**:

I expected the command not to provide an error, but to provide the same hash as provided with v0.18.0.

**How to reproduce it (as minimally and precisely as possible)**:

The problem can be reproduced with the following command sequence using the following constructor file

**constructor.yaml**
```
name: github.com/mandelsoft/test1
version: 1.0.0
provider:
  name: mandelsoft.org
resources:
  - name: multi
    type: plainText
    version: v1
    input:
      type: utf8
      text: test data
  - name: multi
    type: plainText
    version: v2
    input:
      type: utf8
      text: extended test data
```

- create CTF with v0.18.0
  ```
  $ ocm.v18 add cv -c -F test.ctf  constructor.yaml
  ```

- hash component with main version
  ```
  $ ocm.main hash cv -N jsonNormalisation/v2 test.ctf
  ```

  It provides the following output:
  ```
  2025-01-11T12:14:49+01:00 warning [ocm/compdesc/normalizations/legacy] "resource identity duplication was normalized for backwards compatibility, to avoid this either specify a unique extra identity per item or switch to jsonNormalisation/v3" "extra identity"="\"version\"=\"v1\"" index=0 name=multi
  COMPONENT                   VERSION HASH
  github.com/mandelsoft/test1 1.0.0   error: github.com/mandelsoft/test1:1.0.0: failed propagating digest context: digest set for github.com/mandelsoft/test1:1.0.0 does not match
  ```

**Anything else we need to know**:

I would guess that this error occurs, because the new v1/v2 normalization implementations change the component descriptor. It does not happen with v3.

**Environment**:
