### ISSUE TITLE
Method GetIdentity for CD format versions not fixed

### ISSUE THREAD

**Issue by mandelsoft** [open-component-model/ocm#1246]
**What happened**:

With v0.19.0 the method `GetIdentity` was fixed for the internal CD version. Unfortunately this fix was not done for the appropriate methods on
the format versions.

As a result, for resource sets like

```yaml
- access: null
  extraIdentity:
    version: v1
  name: res
  type: ""
  version: v1
- access: null
  name: res
  type: ""
  version: v2
```
with a mixed specification of a required version field in the extra identity, the identity is not correctly calculated (for the second resource, the version is not part of the identity).

This method is only used by the local CD validation.  User coding is not affected, but therefore the method cannot be removed at all.

**What you expected to happen**:

For both resources the version must be part of the identity.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:
