### ISSUE TITLE
`ocm get resources ./ocm/cft/ --latest -r` fails for `componentReferences:` -> likely bug at resolver usage for references in the download resource command

### ISSUE THREAD

**Issue by sk31337** [open-component-model/ocm#1505]
**Context**  
Hello colleagues,

i have a component-constructor which has a reference to two other ocm components.
```yaml
components:
  - name: github.com/platform-mesh/httpbin-operator
    version: "${artifactVersion}"
    provider:
      name: platform-mesh
    resources:
      [....]
    componentReferences:      
      - name: http-bin-ui
        componentName: github.com/platform-mesh/httpbin-ui
        version: 0.2.1
        # docker pull component-descriptors/github.com/platform-mesh/httpbin-ui:0.2.1
      - name: kcp-dev-api-syncagent
        componentName: github.com/kcp-dev/api-syncagent
        version: 0.0.1
```

```bash
ocm add components --create --file ./ocm/cft ./ocm/component-constructor.yaml artifactVersion=$(cat VERSION)
processing ./ocm/component-constructor.yaml...
  processing document 1...
    processing index 1
found 1 component
adding component github.com/platform-mesh/httpbin-operator:0.4.21...
  adding resource helmChart: "name"="oci-helm-chart-httpbin-operator","version"="0.4.21"...
  adding resource helmChart: "name"="oci-helm-chart-httpbin-operator-crds","version"="0.4.21"...
  adding resource ociImage: "name"="image-httpbin-operator","version"="0.4.21"...
  adding resource blob: "name"="kro-rgd","version"="0.4.21"...
  adding reference github.com/platform-mesh/httpbin-ui: "name"="http-bin-ui","version"="0.2.1"...
  adding reference github.com/kcp-dev/api-syncagent: "name"="kcp-dev-api-syncagent","version"="0.0.1"...
```

ocm add works fine, but when i want to look at the resources, i get this error:

```bash
ocm get resources ./ocm/cft/ --latest -r                                       
Warning: lookup nested component version "github.com/platform-mesh/httpbin-ui":0.2.1 [github.com/platform-mesh/httpbin-operator:0.4.21]: component version "github.com/platform-mesh/httpbin-ui:0.2.1" not found: oci artifact "0.2.1" not found in component-descriptors/github.com/platform-mesh/httpbin-ui
Warning: lookup nested component version "github.com/kcp-dev/api-syncagent":0.0.1 [github.com/platform-mesh/httpbin-operator:0.4.21]: component version "github.com/kcp-dev/api-syncagent:0.0.1" not found: oci artifact "0.0.1" not found in component-descriptors/github.com/kcp-dev/api-syncagent
REFERENCEPATH                                    NAME                                 VERSION IDENTITY TYPE      RELATION
github.com/platform-mesh/httpbin-operator:0.4.21 image-httpbin-operator               0.4.21           ociImage  external
github.com/platform-mesh/httpbin-operator:0.4.21 kro-rgd                              0.4.21           blob      local
github.com/platform-mesh/httpbin-operator:0.4.21 oci-helm-chart-httpbin-operator      0.4.21           helmChart external
github.com/platform-mesh/httpbin-operator:0.4.21 oci-helm-chart-httpbin-operator-crds 0.4.21           helmChart external
```

The references components are there:

```bash
ocm get cv ghcr.io/platform-mesh/ocm//github.com/kcp-dev/api-syncagent --latest -r
REFERENCEPATH COMPONENT                        VERSION PROVIDER      IDENTITY
              github.com/kcp-dev/api-syncagent 0.0.1   platform-mesh 

ocm get cv ghcr.io/platform-mesh/ocm//github.com/platform-mesh/httpbin-ui:0.2.1 -r    
REFERENCEPATH COMPONENT                           VERSION PROVIDER      IDENTITY
              github.com/platform-mesh/httpbin-ui 0.2.1   platform-mesh 
```

When i pushed cft to an oci registry, the lookup works:
```bash
ocm get resources ghcr.io/platform-mesh/ocm//github.com/platform-mesh/httpbin-operator --latest -r
REFERENCEPATH                                                                               NAME                                 VERSION IDENTITY TYPE      RELATION
github.com/platform-mesh/httpbin-operator:0.4.21                                            image-httpbin-operator               0.4.21           ociImage  external
github.com/platform-mesh/httpbin-operator:0.4.21                                            kro-rgd                              0.4.21           blob      local
github.com/platform-mesh/httpbin-operator:0.4.21                                            oci-helm-chart-httpbin-operator      0.4.21           helmChart external
github.com/platform-mesh/httpbin-operator:0.4.21                                            oci-helm-chart-httpbin-operator-crds 0.4.21           helmChart external
github.com/platform-mesh/httpbin-operator:0.4.21->github.com/kcp-dev/api-syncagent:0.0.1    helm-chart-api-syncagent             0.0.1            helmChart external
github.com/platform-mesh/httpbin-operator:0.4.21->github.com/kcp-dev/api-syncagent:0.0.1    image-api-syncagent                  0.0.1            ociImage  external
github.com/platform-mesh/httpbin-operator:0.4.21->github.com/platform-mesh/httpbin-ui:0.2.1 image-httpbin-operator-ui            0.2.1            ociImage  external
github.com/platform-mesh/httpbin-operator:0.4.21->github.com/platform-mesh/httpbin-ui:0.2.1 oci-helm-chart-httpbin-operator-ui   0.2.1            helmChart external
```

As @jakobmoellerdev stated in Slack: It is likely bug at resolver usage for references in the download resource command.

```bash
cat $HOME/.ocmconfig
type: generic.config.ocm.software/v1
configurations:
- type: credentials.config.ocm.software
  consumers:
      - identity:
          type: OCIRegistry
          hostname: ghcr.io
        credentials:
          - type: Credentials
            properties:
              username: sk31337
              password: ghp_.....
  repositories:
    - repository:
        type: DockerConfig/v1
        dockerConfigFile: "~/.docker/config.json"
        propagateConsumerIdentity: true
- type: attributes.config.ocm.software
  attributes:
    cache: ~/.ocm/cache
```

**Version**  
v0.20.0

**To Reproduce**  

**Actual behavior**  
A clear and concise description of what is happening.

**Expected behavior**  

**Screenshots (optional)**  

**Environment**  
- [ ] windows
- [ ] linux
- [x] mac

**Additional Comments**  
Any observation, gut feeling or other information you think help the community to troubleshoot the problem?

**Comment by Skarlso** [comment]
Reproduced with latest version:
```
➜ ocm get resources ./ocm/cft/ --latest -r
Warning: lookup nested component version "github.com/platform-mesh/httpbin-ui":0.2.1 [github.com/platform-mesh/httpbin-operator:1.0.0]: component version "github.com/platform-mesh/httpbin-ui:0.2.1" not found: oci artifact "0.2.1" not found in component-descriptors/github.com/platform-mesh/httpbin-ui
Warning: lookup nested component version "github.com/kcp-dev/api-syncagent":0.0.1 [github.com/platform-mesh/httpbin-operator:1.0.0]: component version "github.com/kcp-dev/api-syncagent:0.0.1" not found: oci artifact "0.0.1" not found in component-descriptors/github.com/kcp-dev/api-syncagent
REFERENCEPATH                                   NAME  VERSION IDENTITY TYPE     RELATION
github.com/platform-mesh/httpbin-operator:1.0.0 image 1.0.0            ociImage external
```

**Comment by Skarlso** [comment]
I'm going to try with some different component references...

**Comment by Skarlso** [comment]
Same with public components.

```
➜ ocm get resources ./ocm/cft/ --latest -r
Warning: lookup nested component version "ocm.software/toi/installers/helminstaller":0.12.0 [github.com/platform-mesh/httpbin-operator:1.0.0]: component version "ocm.software/toi/installers/helminstaller:0.12.0" not found: oci artifact "0.12.0" not found in component-descriptors/ocm.software/toi/installers/helminstaller
REFERENCEPATH                                   NAME  VERSION IDENTITY TYPE     RELATION
github.com/platform-mesh/httpbin-operator:1.0.0 image 1.0.0            ociImage external
```

```yaml
components:
  - name: github.com/platform-mesh/httpbin-operator
    version: 1.0.0
    provider:
      name: platform-mesh
    resources:
      - name: image
        type: ociImage
        version: 1.0.0
        access:
          type: ociArtifact
          imageReference: gcr.io/google_containers/echoserver:1.10
    componentReferences:
    - componentName: ocm.software/toi/installers/helminstaller
      name: installer
      version: 0.12.0
```

**Comment by Skarlso** [comment]
Okay, so... @sk31337 and @jakobmoellerdev 

The reason why nothing is there locally is that you don't have the complete reference graph locally. Basically, all references resides somewhere, right? For a CTF these are not there so it won't have them. However, if you, during the creation, use `complete` in addition with a lookup setting where those component references are, then it will fetch them and add them to the ctf.

Something like this:

With a component constructor such as this:

```yaml
components:
  - name: github.com/platform-mesh/httpbin-operator
    version: 1.0.0
    provider:
      name: platform-mesh
    resources:
      - name: image
        type: ociImage
        version: 1.0.0
        access:
          type: ociArtifact
          imageReference: gcr.io/google_containers/echoserver:1.10
    componentReferences:
    - componentName: ocm.software/toi/installers/helminstaller
      name: installer
      version: 0.12.0
```

Do the following with `--complete` flag:

```
❯ ocm add components --complete --create --file ./ocm/cft components-2.yaml --lookup ghcr.io/open-component-model/ocm
processing components-2.yaml...
  processing document 1...
    processing index 1
found 1 component
adding component github.com/platform-mesh/httpbin-operator:1.0.0...
  adding resource ociImage: "name"="image","version"="1.0.0"...
  adding reference ocm.software/toi/installers/helminstaller: "name"="installer","version"="0.12.0"...
completing github.com/platform-mesh/httpbin-operator:1.0.0...
  transferring version "ocm.software/toi/installers/helminstaller:0.12.0"...
  ...resource 1 toiexecutor[toiExecutor]...
  ...adding component version...
goprojects/sap/ocm-download-bug
➜ ocm get resources ./ocm/cft/ --latest -r
REFERENCEPATH                                                                                     NAME        VERSION IDENTITY TYPE        RELATION
github.com/platform-mesh/httpbin-operator:1.0.0                                                   image       1.0.0            ociImage    external
github.com/platform-mesh/httpbin-operator:1.0.0->ocm.software/toi/installers/helminstaller:0.12.0 toiexecutor 0.12.0           toiExecutor local
github.com/platform-mesh/httpbin-operator:1.0.0->ocm.software/toi/installers/helminstaller:0.12.0 toiimage    0.12.0           ociImage    local
ocm.software/toi/installers/helminstaller:0.12.0                                                  toiexecutor 0.12.0           toiExecutor local
ocm.software/toi/installers/helminstaller:0.12.0                                                  toiimage    0.12.0           ociImage    local
```

Normally, all component references sit in the same repository. But because there is nothing defined, I had to add a lookup where the references are located at.

After that, doing `ocm get resources ./ocm/cft/ --latest -r` works as expected.
