### ISSUE TITLE
repoCtx control baseUrl and subPath

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm#388]
**What would you like to be added**:

How can I control in a repositoryContext what is stored in the `baseUrl` and what in `subPath`?

Using ocm I get:
```
    - type: ociRegistry
      baseUrl: eu.gcr.io
      subPath: .../dev/d058463/microblog
```

In Gardner CD ist is stored like this
```
  repositoryContexts:
    - type: ociRegistry
      baseUrl: eu.gcr.io/.../cnudie/gardener/development
      subPath: null
```

See also: https://github.com/open-component-model/ocm-spec/issues/58

**Why is this needed**:
ocm should give full control about the created component descriptor.
