### ISSUE TITLE
Create S3 access method for OCM

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#40]
Make s3 available as an access method.

```yaml
- access:
      region: eu-central-1
      bucket: skarlso-ocm-bucket
      key: file.tar.gz
      type: S3
    name: s3-server
    relation: external
    type: filesystem
    version: 0.0.1
```
