### ISSUE TITLE
Add integration tests to checks done during PR review

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm#406]
**What would you like to be added**:
Similar to the end-2-end cli test executed on commits in a PR branch, the existing integration tests that are done on the main branch every day should be executed (will take around 5 additional minutes)
**Why is this needed**:
Required to avoid errors introduced to the main branch by detecting them before the merge.

**Comment by morri-son** [comment]
Hi @jensh007 , as discussed it makes much sense to also include the integration tests into the PR checks. I hope it is ok, to place this on you as you have the best knowledge about the current test setup.

**Comment by Skarlso** [comment]
Just call dispatch workflow with a payload describing the version and the branch.

**Comment by Skarlso** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch


```yaml
on:
  repository_dispatch:
    types: [test_result]

jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
```
