### ISSUE TITLE
Better integration of resource.yaml (and source.yaml)

### ISSUE THREAD

**Issue by achimweigel** [open-component-model/ocm#44]
**What would you like to be added**:

One important aspect of a component descriptor is that it could be used to provide an initial declarative description of a component which could be stored in, e.g. a git repo. Currently, this initial declarative description is spread over a file containing the (partial) component descriptor and several resource.yaml files containing references to resources which have to be merged into the component descriptor. 

Unfortunately there is no reference in the component descriptor to the additional resource.yaml files. This makes it hard to understand what belongs to a component because this is not described in the declarative model itself and requires some implicit or additional operational information. A possible solution is referencing resource.yaml files in the component descriptor. Then we have a complete declarative description of the component and a resource.yaml file is something like a syntactical variant to structure your references, such that not everything must be described in one big file.

Another disadvantage is how local resources are specified in the resource.yaml files (at least in the old format).  They have an `input` field instead of an `access` field as external resources:

```yaml
# part of a resource.yaml file
---
type: blueprint # local resource
name: cert-manager-blueprint
relation: local
input:
  type: dir
  path: ./blueprint/cert-manager
  mediaType: application/...
  compress: true
...
---
type: ociImage # external resource
name: sap-btp-service-operator-controller
version: v0.2.7
relation: external
access:
  type: ociRegistry
  imageReference: .../.../somename@sha256:...

```

The input field is modified to an access field, when the resources.yaml file is merged into the component descriptor. This is confusing. It would be better to modify the `input` to an `access` field. This would also allow to specify local resources directly in the component descriptor file instead of always using a separate recource.yaml for them.

```yaml
---
type: blueprint # local resource
name: cert-manager-blueprint
relation: local
access:
  type: dir
  path: ./blueprint/cert-manager
  mediaType: application/...
  compress: true
...

```

The possibility to reference files containing references to resources from within a component descriptor must be described in the OCM specification. because it is an important part of the model. 

Similar problems are with source.yaml files, i.e. files containing references to sources of the component.
