### ISSUE TITLE
ocm cli behaves inconsistent between helm charts and oci images

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm#499]
I create a component version with two resources using the same access methods:
```
components:
- name: github.com/jensh007/my-component
  version: 0.1.0
  provider:
    name: github.com/jensh007
  resources:  
  - name: echo-image
    type: ociImage
    version: "1.0"
    access:
      type: ociArtifact
      imageReference: gcr.io/google-containers/echoserver:1.10  
  - name: mariadb-chart
    type: helmChart
    version: 12.2.7
    access:
      type: helm
      helmChart: mariadb:12.2.7
      helmRepository: https://charts.bitnami.com/bitnami
``` 
Then:
```
ocm add componentversions --create --file ./ctf components.yaml 
``` 
The ctf archive is created as expected and then pushed with including resouces:
```
ocm transfer cv -f --copy-resources ctf  eu.gcr.io/<some-path>/test
``` 
Retrieve it with:
```
ocm get cv -o yaml eu.gcr.io/<some-path>/test//github.com/jensh007/my-component:0.1.0
```
Reponse  is:
```
component:
  componentReferences: []
  name: github.com/jensh007/my-component
  provider: github.com/jensh007
  repositoryContexts:
  - baseUrl: eu.gcr.io
    componentNameMapping: urlPath
    subPath: sap-cp-k8s-ocm-gcp-eu30-dev/dev/d058463/test
    type: OCIRegistry
  resources:
  - access:
      imageReference: eu.gcr.io/sap-cp-k8s-ocm-gcp-eu30-dev/dev/d058463/test/google-containers/echoserver:1.10
      type: ociArtifact
    name: echo-image
    relation: external
    type: ociImage
    version: "1.0"
  - access:
      globalAccess:
        digest: sha256:c9889f722eafeaaf2969136d468fa2153f6257ff7ef1341c63f6ee8a7d9ff1b9
        mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
        ref: eu.gcr.io/sap-cp-k8s-ocm-gcp-eu30-dev/dev/d058463/test/component-descriptors/github.com/jensh007/my-component
        size: 46173
        type: ociBlob
      localReference: sha256:c9889f722eafeaaf2969136d468fa2153f6257ff7ef1341c63f6ee8a7d9ff1b9
      mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
      type: localBlob
    name: mariadb-chart
    relation: external
    type: helmChart
    version: 12.2.7
  sources: []
  version: 0.1.0
meta:
  schemaVersion: v2
```

Both resources are originally references to external locations. Both are accessible by corresponding tools like `docker` or `helm`.
After transport the image can be pulled from the new location, but `helm` is not able to retrieve the chart.

Expectation would be that the helm chart is an oci resource accessible by helm.
