### ISSUE TITLE
Merge of PR #483 breaks integration tests

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm#513]
Since merging the PR integration tests are failing:
See e.g. [Run log](https://github.com/open-component-model/ocm-integrationtest/actions/runs/6256334280/job/16986997486)

I can reproduce the error also when running the tests locally. First analysis:

- It seems that he behavior of `ocm push -f --copy-resources` has changed

Input is like:
```
    components:
    ...
        resources:
          - name: image
            type: ociImage
            version: "1.10"
            access:
                type: ociArtifact
                imageReference: gcr.io/google_containers/echoserver:1.10
...
``` 
After pushing with the mentioned parameters the remote comp-descr in the oci registry contains in `access/imageReference`a URL. Now the host name and path is different after PR-merge.
before: `'<host>:<port>/inttest/google_containers/echoserver:1.10'` 
now: `'gcr.io/google_containers/echoserver:1.10'`
