### ISSUE TITLE
OCM is unable to pull content from quay.io for transporting

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#532]
**What happened**:

I have an OCI repository sitting on quay.io like `quay.io/jetstack/cert-manager-cainjector:v1.13.1`.

Trying to transfer this to my own repository ended up with this error message:

```
 2023-10-03T17:43:34+02:00 info    [ocm] "adding resource blob" resource=cert-manager-cainjector
Failed to transfer CTF:  cannot transfer version v1.13.1 for component ocm.software/mpas/cert-manager: ocm.software/mpas/cert-manager:v1.13.1: transferring resource 2: unable to add blob (component ocm.software/mpas/cert-manager:v1.13.1 resource cert-manager-cainjector): unable to add blob (OCI repository skarlso/mpas-bootstrap-with-cert-manager-with-quay/component-descriptors/ocm.software/mpas/cert-manager): failed to push: unexpected status from HEAD request to https://ghcr.io/v2/skarlso/mpas-bootstrap-with-cert-manager-with-quay/component-descriptors/ocm.software/mpas/cert-manager/blobs: 405 Method Not Allowed
```

After manually transporting the image to my own ghcr repository ( not that the quay.io image is _public_ ) with crane, the transport worked.

In addition, this error message is confusing because the problem was not at the target blobs, but at the source location.

**What you expected to happen**:

The transfer to work.

**How to reproduce it (as minimally and precisely as possible)**:

Use the following component:

```yaml
components:
# -- product component
- name: ocm.software/cert-manager
  version: 1.0.0
  provider:
    name: skarlso
  resources:
  - name: image
    relation: external
    type: ociImage
    version: 1.13.1
    access:
      type: ociArtifact
      imageReference: quay.io/jetstack/cert-manager-cainjector:v1.13.1
  - name: image
    relation: external
    type: ociImage
    version: 1.13.1
    access:
      type: ociArtifact
      imageReference: quay.io/jetstack/cert-manager-controller:v1.13.1
  - name: image
    relation: external
    type: ociImage
    version: 1.13.1
    access:
      type: ociArtifact
      imageReference: quay.io/jetstack/cert-manager-webhook:v1.13.1
```

And then build the component and transfer:

```
ocm add componentversions --create  components.yaml -f
processing components.yaml...
  processing document 1...
    processing index 1
found 1 component
adding component ocm.software/cert-manager:1.0.0...
  adding resource ociImage: "name"="image","version"="1.13.1"...
  adding resource ociImage: "name"="image","version"="1.13.1"...
  adding resource ociImage: "name"="image","version"="1.13.1"...


ocm transfer component ./transport-archive ghcr.io/skarlso/cert-manager-test -V -f
transferring version "ocm.software/cert-manager:1.0.0"...
...resource 0(jetstack/cert-manager-webhook:v1.13.1)...
Error: ocm.software/cert-manager:1.0.0: transferring resource 0: unable to add blob (component ocm.software/cert-manager:1.0.0 resource image): unable to add blob (OCI repository skarlso/cert-manager-test/component-descriptors/ocm.software/cert-manager): cannot get blob content: failed to do request: Head "https://quay.io/v2/jetstack/cert-manager-webhook/manifests/v1.13.1": EOF
1 versions transferred
Error: transfer finished with 1 error(s)

```

**Anything else we need to know**:

**Environment**:
