### ISSUE TITLE
Template repository to be update to include Go specific file

### ISSUE THREAD

**Issue by robertwol** [open-component-model/ocm#582]
- We need to add GO lang specific file: `.golangci.yaml`

- Include `.gitignore`

- Create `dependabot.yml` with configuration in the template repository.
 only focus on minor versions and patches. ref: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

**Comment by robertwol** [comment]
Hi @Skarlso  cc' @phoban01 

I think you have mentioned the `.golangci.yaml` to be included in the template repo. Could you confirm and provide the good example. so far I looked at the `.golangci.YAML` in this repo. is it good example?
Are there any other files that should be incldued?

**Comment by Skarlso** [comment]
```yaml
un:
  go: "1.21"
  timeout: 10m
  tests: false
  allow-parallel-runners: true
  skip-dirs:
    - "./*/mock"

linters-settings:
  funlen:
    lines: 110
    statements: 60
  staticcheck:
    go: "1.21"
  stylecheck:
    go: "1.21"
  cyclop:
    max-complexity: 15
    skip-tests: true
  gosec:
    exclude-generated: true
  lll:
    line-length: 120
  misspell:
    locale: US
  govet:
    check-shadowing: true
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: false
  varnamelen:
    ignore-names:
      - err
      - wg
      - fs
      - id
      - vm
      - ns
      - ip

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    - text: "should not use dot imports|don't use an underscore in package name"
      linters:
        - golint
    - source: "https://"
      linters:
        - lll
    - path: pkg/defaults/
      linters:
        - lll
    - path: _test\.go
      linters:
        - goerr113
        - gocyclo
        - errcheck
        - gosec
        - dupl
        - funlen
        - scopelint
        - testpackage
    - path: internal/version/
      linters:
        - gochecknoglobals
    - path: internal/command/
      linters:
        - exhaustivestruct
        - lll
        - wrapcheck
    - source: "// .* #\\d+"
      linters:
        - godox
    - path: test/e2e/
      linters:
        - goerr113
        - gomnd
    # remove this once https://github.com/golangci/golangci-lint/issues/2649 is closed
    - path: /
      linters:
        - typecheck

linters:
  enable-all: true
  disable:
    - gci
    - depguard
    - exhaustivestruct
    - golint
    - interfacer
    - ireturn
    - maligned
    - nilnil
    - scopelint
    - tagliatelle
    - gomoddirectives
    - varcheck
    - nosnakecase
    - structcheck
    - ifshort
    - deadcode
    - forbidigo
    - prealloc
    - gochecknoinits
    - exhaustruct
    - goerr113
    - govet
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - staticcheck
```
