### ISSUE TITLE
ocm tranfer ctf --overwrite not working on resource input property changes

### ISSUE THREAD

**Issue by reshnm** [open-component-model/ocm#617]
**What happened**:

`ocm transfer ctd -f|--overwrite` refuses to overwrite an already existing component version when only a property o a resource input is changed.

**What you expected to happen**:

The exiting component version shall be overwritte.

**How to reproduce it (as minimally and precisely as possible)**:

Assume a component with a resource like this:

```yaml
- name: my-chart
   type: helm.io/chart
   version: v0.1.0
   input:
     type: helm
     helmRepository: https://my-helm.repo
     path: my-chart
     version: v0.1.0
     repository: charts/my-chaaaaaaaart
```

create a component version:

```sh
ocm add componentversions --create --file ....
```

transfer it

```sh
ocm transfer ctf --copy-resources ...
``` 

Change a property of the resource input:

```yaml
- name: my-chart
   type: helm.io/chart
   version: v0.1.0
   input:
     type: helm
     helmRepository: https://my-helm.repo
     path: my-chart
     version: v0.1.0
     repository: charts/my-chart
```

create a component version (identical version):

```sh
ocm add componentversions --create --file ....
```

transfer it and specify the force overwrite flaf (-f, --overwrite) 

```sh
ocm transfer ctf --copy-resources --overwrite ...
```

The transport is being skipped:

```sh
transferring component ..
  transferring version ...
    version ... already present -> skip transport
```

**Environment**:

```sh
ocm version
{"Major":"0", "Minor":"6", "Patch":"0", "PreRelease":"", "Meta":"", "GitVersion":"0.6.0", "GitCommit":"dfcf27e5f22d83feac7869e0f303c6e6e66f1e8d", "GitTreeState":"", "BuildDate":"2023-12-29T14:31:58Z", "GoVersion":"go1.21.5", "Compiler":"gc", "Platform":"darwin/arm64"}
```
