### ISSUE TITLE
Add configuration options on how to handle multi-arch oci images during transfer

### ISSUE THREAD

**Issue by reshnm** [open-component-model/ocm#621]
**What would you like to be added**:

One can define an oci image as an `ociArtifact` input type like this:

```yaml
- name: cert-manager-controller
   type: ociImage
   version: ${CERT_MANAGER_VERSION}
   input:
     type: ociArtifact
     path: quay.io/jetstack/cert-manager-controller:${CERT_MANAGER_VERSION}
     repository: images/cert-manager/cert-manager-controller
```

During transfer (`ocm transfer ctf --copy-resources`) the oci image is transferred to the location defined in property `repository`.
When the oci image is a multi-arch image, all archrchitectures ar copied.

I would be benificial to be able to allow a user to specify a instruction on how to handle multi-arch images during transfer.
The default would behave like the current implementation and transfer all architectures.

I think it would be sufficient to have a command line parameter in ocm transfer where the archs that shall be transferred can be specified.

e.g.:
```sh
ocm transfer ctf --copy-resources --oci-image-multiarch-filter="amd64,arm64"
```

**Why is this needed**:

Storage is costly and users might to avoid saving images that are never used. When the user knows that the component only supports amd64, storing all architectures would be wasteful.
