### ISSUE TITLE
Add OCI image resource fails when a cache directory is specified on Windows

### ISSUE THREAD

**Issue by markrexwinkel** [open-component-model/ocm#677]
**What happened**:

When adding an OCI image resource to a component archive an error occured:

```
processing resource (by options)...
  processing document 1...
    processing index 1
found 1 resource
adding resource ociImage: "name"="bitnami-shell","version"="10"...
Error: cannot add resource "bitnami-shell"(resource (by options)[1][1]): cannot determine digest: failed to get blob data: rename C:/Users/markr/.ocm/cache/TMPe7fdacaf-0b68-4424-af5b-014fb20c454d C:/Users/markr/.ocm/cache/sha256.6ad5f7271222857fff8d51e5204f5f7b3a43c34d14c8a9bc77598443d9102562: The process cannot access the file because it is being used by another process.
```

**What you expected to happen**:

The image is added to the component archive without errors.

**How to reproduce it (as minimally and precisely as possible)**:

Make sure a cache directory is configured in %USERPROFILE%\.ocmconfig:
```yaml
type: generic.config.ocm.software/v1
configurations:
- type: credentials.config.ocm.software
  repositories:
    - repository:
        type: DockerConfig/v1
        dockerConfigFile: "C:\\Users\\markr\\.docker\\config.json"
        propagateConsumerIdentity: true
- type: attributes.config.ocm.software
  attributes:
    cache: "C:\\Users\\markr\\.ocm\\cache"
```

Then create a component archive and add the image:

```powershell
# Create component archive
ocm create ca --file ca --scheme ocm.software/v3alpha1 --provider test.com test.com/postgresql 14.0.5

# Add OCI image to component archive
ocm add resource --file ca --name bitnami-shell --type ociImage --accessType ociArtifact --version 10 --reference bitnami/postgresql:16.2.0-debian-11-r1
```

**Anything else we need to know**:

The error only occurs when a cache directory is configured in the `.ocmconfig` file. If you leave out the cache directory everything works as expected.
It seems a file is downloaded to the cache folder and then renamed, but the rename fails because the file is not closed yet.

I did not encounter this with ocm 0.6.0

**Environment**:

OS: Windows 11 Pro 23H2
ocm: 0.7.0
