### ISSUE TITLE
[Gap-Close OCM client] Implement `github` Access Method for OCM

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#7]
# Premise

Access methods for OCM require a `github` implementation. How that could look like?

```yaml
name: git-source
access:
  type: github
  repoUrl: github.com/org/repo
  ref: refs/heads/main
version: 0.1.0-dev
type: <arbitrary>
```

## Implementation Notes

The created artefact must be a blob of type TAR which contains the entirety of the repository. Alternatively, there is a REST call for GitHub to provide such a TAR archive.

The first iteration need only concern itself with public repositories. The next iteration will add Credentials and private repositories.

For now, focus on creating an access method under `ocm/accessmethods`.

The full implementation should live in the access method for now. Later, when there is a git `context` we can defer the implementation there and abstract the usage for the access method implementation.

- [ ] `github` access method works and downloads a tar archive of the pointed repository
- [ ] documentation and sample yaml exists to try out this new access method
