### ISSUE TITLE
Credentials for npm repositories have no effect

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm#753]
**What happened**:
Credentials for npm are configured as documented in .ocmconfig or command line:
```
type: generic.config.ocm.software/v1
configurations:
  - type: credentials.config.ocm.software
    consumers:
      - identity:
          type: Registry.npmjs.com
          hostname: common.repositories.cloud.sap
        credentials:
          - type: Credentials
            properties:
              username: gardener-lm-ocm
              password: ...
```

**What you expected to happen**:
Access to private npm registries is possible. But results in 401 http error

**How to reproduce it (as minimally and precisely as possible)**:
any resource with type: npmPackage and located in any private npm registry

**Anything else we need to know**:
The type ` type: Registry.npmjs.com`differs in syntax from all other types (OCIRegisrty, HelmChartRepository) and why a capital R?

**Environment**:
