### ISSUE TITLE
'hint' as part of the artifact specification

### ISSUE THREAD

**Issue by fabianburth** [open-component-model/ocm#935]
# Add `hint` to the artifact specification

### Uploaders
The ocm library has a concept of *uploaders* (also called *blobhandlers*) within the ocm library. These *uploaders*
essentially provide the functionality to upload a *blob* described as an *artifact* (thus, as a *source* or *resource*)
as part of a component to a technology specific storage.

The *uploaders* are an integral part of the ocm transport process. During a *ocm transfer*, *uploaders* can be
configured to be called to upload artifacts to a technology specific repository.

#### Mechanism
The mechanism behind the *uploaders* is explained by answering the following questions.

**How does the ocm decide which *uploader(s)* are called for each particular artifact?**   
There is a *registry* of uploaders where the technology specific *uploaders* can be registered to be called for the set
of (or a subset of) the following properties: **artifact type**, **mime type**, and **implementation repository type**.  
The *implementation repository type* describes the type of repository technology based on which the ocm repository is 
implemented (also referred to as 
[storage backend mapping](https://github.com/open-component-model/ocm-spec/blob/main/doc/04-extensions/03-storage-backends/README.md#storage-backend-mappings)
in the ocm spec). The most common type of repository technology are OCI registries. 

The *implementation repository type* allows for the implementation of default *uploaders* for ocm repository types. For 
example, if the *implementation repository type* is *oci*, an oci *uploader* attempts to upload all artifacts of 
*artifact type* `ociArtifact` as individual oci artifacts (without this uploader, the artifacts would only be available 
as a blob which is described by a layer of the oci artifact representing the respective ocm component). 

> NOTE: In the command line use case, the *uploaders* can be configured based on the ocm configuration (see 
[here](https://github.com/open-component-model/ocm/blob/main/docs/reference/ocm_ocm-uploadhandlers.md).  

**How does each *uploader* know where to upload the artifact to?**
To upload the blob, the *uploaders* get the *blob* itself, the *artifact type*, *mime type*, *implementation repository
type* (so, the information it may be registered for), and a **hint**. The former information is supposed to be used by
the *uploader* to ensure that the artifact is suitable to be uploaded to the corresponding technology specific
repository.  
The *hint*, however, is supposed to contain any further information that might be needed by the uploader to correctly
upload the blob.

**Example**

```yaml
name: image
relation: external
type: ociArtifact
version: v1.0.0
access: 
  type: maven
  repoUrl: https://maven.central.org
  coordinates: ocm/software/1.0.0/image.tar.gz
  hint: ocm.software/ocm-cli:v1.0.0
```

Assume, we configured exactly one *uploader* with the following configuration:

```yaml
type: uploader.ocm.config.ocm.software                                                                          
handlers:                                                                                                       
- name: ocm/ociArtifacts                                                                                          
  artifactType: ociArtifact                                                                                     
  config:
    ociRef: https://ghcr.io/open-component-model//maven
```

This registers an *OCI uploader* for *artifact type* `ociArtifact`. As described above, consequently, the *OCI uploader* 
is called during transfer for this artifact (and all other artifacts of type `ociArtifact` in our hypothetical
component). As a result, the `image.tar.gz` file in the maven package would be uploaded to
`https://ghcr.io/open-component-model/maven/ocm.software/ocm-cli:v1.0.0`.

**ISSUE 1:**  
The current oci uploader would attempt to check the media type of the blob described by the maven
access. Since a GAVCE can always match with multiple files (e.g. based on the above example, if the maven package
contains a file `ocm-cli-image.tar.gz` and another file `ocm-website-image.tar.gz`), the maven access method currently
returns all blobs as `tar.gz` with the corresponding media type `application/x-tar`. 
If the GAVCE contains multiple files, it is necessary to create a tar-archive. But if our intention was to specify a 
particular file with the GAVCE - as is in our above example, where we want to specify a particular oci artifact - it is 
rather inconvenient that it is tar'ed, since the current implementation of the oci upload handler cannot deal with a 
tar.gz.tar.gz file. Of course, we could provide a special upload handler that knows how to do this, but this is 
inconvenient.   
If we assume, we resolved above problem and return single files exactly as they are, we would still have to know the 
media type of the file specified by the GAVCE. Thus, an additional property `mediaType` is needed within the maven input 
and access spec.

**ISSUE 2:**
Currently, the `hint` is provided by the access method. That is because the current access method might be able to
provide a `hint`. For example, if you have a artifact with an `ociArtifact` access type. If you transfer the component
including the resources to another registry without having *uploaders* registered, the access type will be changed to
`localBlob`.

So, it will be converted from:

```yaml
name: image
relation: external
type: ociArtifact
version: v1.0.0
access: 
  type: ociArtifact
  imageReference: https://ghcr.io/open-component-model/ocm/ocm-cli@<image-digest>
```

to:

```yaml
name: image
relation: external
type: ociArtifact
version: v1.0.0
access: 
  type: localBlob
  localReference: <image-digest>
  mediaType: application/vnd.oci.image.manifest.v1+json
  referenceName: ocm/ocm-cli
```

Thereby, the `ociArtifact` access method provides the `hint` which is then stored in the `referenceName` of the
`localBlob` access spec to be able to upload the artifact to a similiar location in another registry, if the blob would
be transferred again with a oci *uploader* registered. Consequently, the `localBlob` access method would then provide 
the `referenceName` as `hint` during that upload.

## Suggestion 1

Since the concept of *uploaders* is more generic than this oci use case and since the `hint` is independent of the
access specification of the artifact, I suggest that we extend the ocm specification to make the `hint` an additional 
optional property of artifacts (thus, parallel to the `type` of an artifact).  
Since `hints` are specific to the type of repository the artifact should be uploaded to or rather even specific to the
type of uploader (e.g. the `hint` for an oci uploader likely looks different than the `hint` for an npm uploader). 
Moreover, a `hint` might even be specific to a certain *uploader*. **Therefore, I suggest that the `hint` property should 
have a similiar structure as *labels* consisting of a `name (string)`, `value (any)`, and `version (string)`.**

To preempt the question why I would not add a particular *label* for this `hint` instead of adjusting the ocm
specification - that is because, as mentioned above, the concept of *uploaders* (or *blobhandlers*) is an integral part
of the transport process. 

## Suggestion 2

Since the concept described above is primarily necessary if we allow cross-consumption (so to download a blob from one
type of repository, here maven, and upload it to a different type of repository, here oci), **I suggest we decide not to
support cross-consumption at all (at least for now). In that case, we can also omit the hint from the maven spec!**
