### ISSUE TITLE
OCI path for a Component

### ISSUE THREAD

**Issue by nexus49** [open-component-model/ocm#984]
**What happened**:
So when create a OCM Component based in the given resource file:
```
components:
  - name: github.com/example-org/example-repo/example-chart
    version: 1.0.0
    provider:
      name: Some Provider
    resources:
      - name: chart
        type: helmChart
        input:
          type: helm
          path: charts/example-chart
``` 

This Component gets transferred to a OCI repository: `example.com/repo/ocm`

When looking at the ocm component using the ocm cli it looks like this:
```
ocm get components --repo example.com/repo/ocm github.com/example-org/example-repo/example-chart -oyaml
---
component:
  componentReferences: []
  creationTime: "2024-10-18T09:43:04Z"
  name: github.com/example-org/example-repo/example-chart
  provider: Some Provider
  repositoryContexts:
  - baseUrl: example.com
    componentNameMapping: urlPath
    subPath: repo/ocm
    type: OCIRegistry
  resources:
  - access:
      imageReference: example.com/repo/ocm/github.com/example-org/example-repo/example-chart/example-chart:1.0.0@sha256:6fafeca3d51ebf5fe110a9b5c7d7ffc2892346733d23e96500f171a6e50d3853
      type: ociArtifact
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: ociArtifactDigest/v1
      value: 6fafeca3d51ebf5fe110a9b5c7d7ffc2892346733d23e96500f171a6e50d3853
    name: chart
    relation: local
    type: helmChart
    version: 1.0.0
  sources: []
  version: 1.0.0
meta:
  schemaVersion: v2
```

When this OCM Component is being used to be deployed using the ocm controller you'd define the following Resource:
```
apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: example-chart
  namespace: default
spec:
  interval: 10m0s
  component: github.com/example-org/example-repo/example-chart
  repository:
    url: example.com/repo/ocm/github.com/example-org/example-repo/example-chart
  version:
    semver: 1.0.0
```

Basically I have to use the component name when using the Resource File, OCM CLI and the Component Version.

When looking at the OCI Resource path (access imageReference) it contains an additional `example-chart`:
`example.com/repo/ocm/github.com/example-org/example-repo/example-chart/example-chart`

This leads to weird behaviors, when one would for example try to use renovate to update the version of a component based on renovate for deployment scenarios.

**What you expected to happen**:
I'd expect that the OCI path follows the same naming format as the component name: `repo/componentname` or `example.com/repo/ocm/github.com/example-org/example-repo/example-chart` in the given example.

**Comment by Skarlso** [comment]
Hello.

The "additional" chart is from the chart name. For example for me:

```
➜  http-source-controller git:(main) ✗ ocm get components --repo ghcr.io/skarlso github.com/skarlso/podinfo-helm -oyaml
---
component:
  componentReferences: []
  name: github.com/skarlso/podinfo-helm
  provider: skarlso.org
  repositoryContexts:
  - baseUrl: ghcr.io
    componentNameMapping: urlPath
    subPath: skarlso
    type: OCIRegistry
  resources:
  - access:
      imageReference: ghcr.io/skarlso/github.com/skarlso/podinfo-helm/podinfo:6.3.5
      type: ociArtifact
    name: charts
    relation: local
    type: helmChart
    version: 6.3.5
  sources: []
  version: v1.0.0
meta:
  schemaVersion: v2
```

The additional chart is `podinfo`. That's the chart's name. It needs to be there so Helm can find the chart. That's a requirements from Helm. 

The other requirement from helm is that the tag of the layer is the same as the helm's version. Otherwise the deploy will fail with an error saying that there is a mismatch between the layer tag and the helm version.

That's why in the access ref you see the version is `6.3.5` and NOT the component version as it would be normally.
